return {
  require 'plugins.dadbod',
  require 'plugins.neo-tree',
  require 'plugins.which-key',
  require 'plugins.vim-tmux-navigator',
  require 'plugins.telescope',
  require 'plugins.nvim-treesitter',
  require 'plugins.nvim-lspconfig',
  require 'plugins.conform-nvim',
  require 'plugins.colorscheme',
  require 'plugins.vim-fugitive',
  require 'plugins.vim-sleuth',
  require 'plugins.nvim-cmp',
  require 'plugins.comments',
  require 'plugins.debug',
  require 'plugins.neotest',
}
